### ISSUE TITLE
RuntimeError： cudaErrorIllegalAddress

### ISSUE THREAD

**Issue by artofstate** [xinge008/Cylinder3D#77]
Hi, when I run the train.sh, I encountered such problem"RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered". Does anyone have any idea?
my environment is:
Ubuntu 18.04
Cuda 11.1
gpu 3090
pytorch1.8.1

**Comment by xinge008** [comment]
To be honest, I do not encounter this issue. Maybe you can provide more details shown in error log.

**Comment by artofstate** [comment]
Thanks a lot . I think it is the reason of cuda.  When I train it with cuda 10.2,I do not encounter this issue .

**Comment by Daisy-GENG** [comment]
The reason maybe here
when you run `import torch_scatter` it will look for cuda 10.2 but not cuda 11.1

As you can test like this:
```bash
>>> import torch_scatter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/torch_scatter/__init__.py", line 14, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
  File "/usr/local/lib/python3.6/dist-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.10.2: cannot open shared object file: No such file or directory

```

**Comment by Daisy-GENG** [comment]
> The reason maybe here when you run `import torch_scatter` it will look for cuda 10.2 but not cuda 11.1
> 
> As you can test like this:
> 
> ```shell
> >>> import torch_scatter
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.6/dist-packages/torch_scatter/__init__.py", line 14, in <module>
>     f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
>   File "/usr/local/lib/python3.6/dist-packages/torch/_ops.py", line 104, in load_library
>     ctypes.CDLL(path)
>   File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: libcudart.so.10.2: cannot open shared object file: No such file or directory
> ```

and finally I found the solution, you need modify Dockerfile totally:
```bash
FROM nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04

# Just in case we need it
ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt upgrade -y
RUN apt install -y python3 python3-dev python3-pip
RUN pip3 install --upgrade pip
RUN apt install -y git wget unzip
RUN apt install -y build-essential
RUN apt install -y ffmpeg libsm6 libxext6

# get newer version of cmake
RUN wget https://apt.kitware.com/kitware-archive.sh
RUN chmod +x kitware-archive.sh && ./kitware-archive.sh

RUN pip3 install torch==1.8.2+cu111 torchvision==0.9.2+cu111 torchaudio==0.8.2 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html
RUN pip3 install pyyaml==5.4.1
RUN pip3 install cython==0.29.24
RUN pip3 install nuscenes-devkit==1.1.6
RUN pip3 install numba==0.53.1
RUN pip3 install strictyaml==1.4.4

# Torch scatter
RUN pip3 install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.1+cu111.html

```
The things modify here:
1. `FROM nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04`
2. `RUN pip3 install torch==1.8.2+cu111 torchvision==0.9.2+cu111 torchaudio==0.8.2 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html`
3. `RUN pip3 install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.1+cu111.html`

Although the torch-scatter cannot correspond to torch 1.8.2 but I found that it can work like here:
![demo](https://user-images.githubusercontent.com/52648643/148415256-83607246-f68a-422a-8425-7a050c38b081.png)

**Comment by GaloisWang** [comment]
https://github.com/taesungp/contrastive-unpaired-translation/issues/83
this can help.
